- name: Error case for Elasticsearch config - although use_cert is true, no cert data are given.
  hosts: all
  become: true
  vars:
    __test_inputfiles_dir: /var/log/inputdirectory

  tasks:
    - block:
        - name: deploy config to send to elasticsearch
          vars:
            logging_outputs:
              - name: elasticsearch_output
                type: elasticsearch
                server_host: logging-es
                server_port: 9200
                index_prefix: project.
                input_type: ovirt
                retryfailures: off
                use_cert: true
            logging_inputs:
              - name: files_input
                type: files
                input_log_path: "{{ __test_inputfiles_dir }}/*.log"
            logging_flows:
              - name: flow_0
                inputs: [files_input]
                outputs: [elasticsearch_output, elasticsearch_output_ops]
          include_role:
            name: linux-system-roles.logging

        - name: unreachable task
          fail:
            msg: UNREACH

      rescue:
        - debug:
            msg: "Caught an expected error - {{ ansible_failed_result.results }}"
        - name: assert...
          assert:
            that: "'{{ ansible_failed_result.results.0.msg }}' is match('Error: you specified use_cert: true; you must specify all 3 of ca_cert, cert, key, or all 3 of ca_cert_src, cert_src, key_src, or set use_cert: false in the elasticsearch output named elasticsearch_output')"
